# 将项目构建镜像并发布至 Docker Hub
name: CI to Docker Hub

# 在 Push 到 main 分支后启动该流程
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 在 GitHub Action 的服务器上 Check Out 源码（整体流程结束后会重置服务器环境因此不需要担心泄露）
      - name: Checkout
        uses: actions/checkout@v3
      # 通用虚拟机
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # 设置 Buildx 为构建镜像做准备
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # 登录至 Docker Hub，账户密码需要在 Settings -> Secrets 中设置
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 构建并发布（执行项目路径下的 Dockerfile 文件）
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy-plus:latest
      # 完成
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}